### ISSUE TITLE
Model Training

### ISSUE THREAD

**Issue by sashaok123** [diontimmer/ControlNet-Trainer#2]
It's a shame to ask, but could you write instructions or shoot a video on how to teach locally on a computer, and not in a colab?

**Comment by diontimmer** [comment]
Local setup instructions are in the readme, is this what you are looking for?

**Comment by sashaok123** [comment]
@diontimmer This is just an installation.
I'm talking about directly using your files to train the model.
I want to write an interface for myself to make it easier to choose folders with datasets and so on, but I don't know where to start from your files.

**Comment by diontimmer** [comment]
as stated in the readme:

To initiate training, run the train.py script with the path of a configuration JSON file as an argument. This configuration file replaces the need for multiple command line arguments. Default configurations can be located within the config.py file, and an example config file is provided for reference. I recommend storing your config files in the configs directory, but they can be placed wherever you find convenient. NOTE: Make sure your dataset is in the format needed by the original ControlNet repo: https://github.com/lllyasviel/ControlNet/blob/main/docs/train.md

you run the train.py script using python, with a path to a config file as the only argument.

you could have your interface build this json :)

**Comment by sashaok123** [comment]
Thank you very much!

**Comment by sashaok123** [comment]
@diontimmer I can't figure out how to work with the file "config.py " and "/configs/example.json".
Which of them to configure and how to run together with the script "train.py "
